'use strict';
const KEY='genevieveSmartShopDataV1';
const PIN_KEY='genevieveSmartShopPinV1';
const defaultData={settings:{cycleDays:14,minimumSpend:50,traceDairy:true,lastShopDate:null},products:[],prices:[],currentShop:[],history:[]};
let data=loadData();let deferredPrompt=null;
const $=id=>document.getElementById(id);const money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(n)||0);const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function loadData(){try{return {...structuredClone(defaultData),...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultData)}}
function saveData(){localStorage.setItem(KEY,JSON.stringify(data));renderAll()}
async function hashPin(pin){const bytes=new TextEncoder().encode('genevieve-smart-shop:'+pin);const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
async function setupPin(){const pin=prompt('Choose a private passcode of at least 4 numbers or characters.');if(!pin||pin.length<4){toast('Passcode was not changed.');return}localStorage.setItem(PIN_KEY,await hashPin(pin));toast('Private passcode saved.');$('pinInput').value=''}
async function unlock(){const stored=localStorage.getItem(PIN_KEY);if(!stored){await setupPin();return}if(await hashPin($('pinInput').value)!==stored){toast('That passcode is not correct.');return}$('lockScreen').classList.add('hidden');$('app').classList.remove('hidden');$('pinInput').value='';renderAll()}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function safetyLabel(v){return v==='approved'?'Approved':v==='check'?'Needs checking':'Blocked'}
function latestPrice(productId,store){return data.prices.filter(p=>p.productId===productId&&p.store===store).sort((a,b)=>new Date(b.date)-new Date(a.date))[0]||null}
function bestFor(product){const c=latestPrice(product.id,'Coles'),w=latestPrice(product.id,'Woolworths');if(!c&&!w)return{store:'Price needed',price:0,c,w};if(!w||c&&c.price<=w.price)return{store:'Coles',price:c.price,c,w};return{store:'Woolworths',price:w.price,c,w}}
function suggestedQty(p){const learned=data.history.flatMap(h=>h.items||[]).filter(i=>i.productId===p.id);if(!learned.length)return Math.max(0,(Number(p.usualQty)||0)-(Number(p.stock)||0));const avg=learned.reduce((s,i)=>s+Number(i.qty||0),0)/learned.length;return Math.max(0,Math.round(avg)-(Number(p.stock)||0))}
function renderDashboard(){const approved=data.products.filter(p=>p.safety==='approved');$('safeCount').textContent=approved.length;$('dueCount').textContent=approved.filter(p=>suggestedQty(p)>0).length;const shopCalc=calculateShop();$('estimatedTotal').textContent=money(shopCalc.total);$('estimatedSaving').textContent=money(shopCalc.saving);const last=data.settings.lastShopDate?new Date(data.settings.lastShopDate):new Date();const next=new Date(last);next.setDate(next.getDate()+Number(data.settings.cycleDays||14));$('nextShopDate').textContent=`Next suggested shop: ${next.toLocaleDateString('en-AU',{day:'numeric',month:'long',year:'numeric'})}`}
function renderProducts(){const q=$('productSearch').value.toLowerCase(),f=$('safetyFilter').value;const list=data.products.filter(p=>(f==='all'||p.safety===f)&&[p.name,p.brand,p.category].join(' ').toLowerCase().includes(q));$('productList').innerHTML=list.length?list.map(p=>`<article class="product-card"><div><div class="item-title">${esc(p.name)}</div><div class="item-sub">${esc(p.brand||'No brand')} · ${esc(p.pack||'Pack size not set')}</div></div><div><span class="badge ${p.safety}">${safetyLabel(p.safety)}</span></div><div><strong>${p.stock||0}</strong><div class="item-sub">currently on hand</div></div><div><strong>${suggestedQty(p)}</strong><div class="item-sub">suggested next shop</div></div><button class="secondary" onclick="editProduct('${p.id}')">Edit</button></article>`).join(''):'<div class="card empty">No products found. Add your first approved product.</div>';renderProductOptions()}
function renderProductOptions(){$('priceProduct').innerHTML='<option value="">Select product</option>'+data.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}
function renderPrices(){const latest=[];for(const p of data.products){for(const s of ['Coles','Woolworths']){const pr=latestPrice(p.id,s);if(pr)latest.push({...pr,product:p})}}$('priceList').innerHTML=latest.length?latest.sort((a,b)=>a.product.name.localeCompare(b.product.name)).map(x=>`<article class="price-card"><div><div class="item-title">${esc(x.product.name)}</div><div class="item-sub">${esc(x.product.brand||'')}</div></div><strong>${x.store}</strong><strong>${money(x.price)}</strong><div class="item-sub">${esc(x.pack||x.product.pack||'')} ${x.unit?`· ${esc(x.unit)}`:''}</div><span class="badge ${x.special?'approved':'check'}">${x.special?'Special':'Regular'}</span></article>`).join(''):'<div class="card empty">No prices saved yet.</div>'}
function calculateShop(){let total=0,singleColes=0,singleWoolies=0;for(const i of data.currentShop){const p=data.products.find(x=>x.id===i.productId);if(!p||p.safety!=='approved')continue;const b=bestFor(p),q=Number(i.qty)||0;total+=b.price*q;singleColes+=(b.c?.price||b.price)*q;singleWoolies+=(b.w?.price||b.price)*q}const oneStore=Math.min(singleColes||Infinity,singleWoolies||Infinity);return{total,saving:Number.isFinite(oneStore)?Math.max(0,oneStore-total):0}}
function renderShop(){const rows=data.currentShop.map(i=>{const p=data.products.find(x=>x.id===i.productId);if(!p)return'';const b=bestFor(p);return`<article class="shop-item"><div><div class="item-title">${esc(p.name)}</div><div class="item-sub"><span class="badge ${p.safety}">${safetyLabel(p.safety)}</span> ${p.noSub?'· No substitutions':''}</div></div><div class="qty-control"><button onclick="changeQty('${i.productId}',-1)">−</button><strong>${i.qty}</strong><button onclick="changeQty('${i.productId}',1)">+</button></div><strong>${b.store}</strong><strong>${b.price?money(b.price*i.qty):'Add price'}</strong><button class="danger" onclick="removeShopItem('${i.productId}')">Remove</button></article>`}).join('');$('shopList').innerHTML=rows||'<div class="card empty">Your shopping list is empty. Press “Add due items”.</div>';let ct=0,wt=0,cc=0,wc=0;for(const i of data.currentShop){const p=data.products.find(x=>x.id===i.productId);if(!p||p.safety!=='approved')continue;const b=bestFor(p);if(b.store==='Coles'){ct+=b.price*i.qty;cc++}if(b.store==='Woolworths'){wt+=b.price*i.qty;wc++}}$('colesTotal').textContent=money(ct);$('wooliesTotal').textContent=money(wt);$('combinedTotal').textContent=money(ct+wt);$('colesCount').textContent=`${cc} item${cc===1?'':'s'}`;$('wooliesCount').textContent=`${wc} item${wc===1?'':'s'}`;const calc=calculateShop();$('shopSaving').textContent=`Saving ${money(calc.saving)}`;const min=Number(data.settings.minimumSpend)||0;const warn=[];if(ct>0&&ct<min)warn.push(`Coles is ${money(min-ct)} below your ${money(min)} preferred minimum.`);if(wt>0&&wt<min)warn.push(`Woolworths is ${money(min-wt)} below your ${money(min)} preferred minimum.`);$('minimumWarning').classList.toggle('hidden',!warn.length);$('minimumWarning').innerHTML=warn.length?`<h3>Minimum-spend check</h3><p>${warn.join(' ')}</p>`:''}
function renderHistory(){$('historyList').innerHTML=data.history.length?data.history.slice().reverse().map(h=>`<article class="history-card"><div class="section-heading"><div><div class="item-title">Shop completed ${new Date(h.date).toLocaleDateString('en-AU')}</div><div class="item-sub">${h.items.length} products recorded</div></div><strong>${money(h.total)}</strong></div><p>${h.items.map(i=>{const p=data.products.find(x=>x.id===i.productId);return `${esc(p?.name||'Deleted product')} × ${i.qty}`}).join(' · ')}</p></article>`).join(''):'<div class="card empty">No completed shops yet.</div>'}
function renderSettings(){$('cycleDays').value=data.settings.cycleDays||14;$('minimumSpend').value=data.settings.minimumSpend??50;$('traceDairy').checked=data.settings.traceDairy!==false}
function renderAll(){renderDashboard();renderProducts();renderPrices();renderShop();renderHistory();renderSettings()}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
window.editProduct=id=>{const p=data.products.find(x=>x.id===id);$('productDialogTitle').textContent='Edit product';$('productId').value=p.id;$('productName').value=p.name;$('productBrand').value=p.brand||'';$('productCategory').value=p.category||'';$('productPack').value=p.pack||'';$('productSafety').value=p.safety;$('productQty').value=p.usualQty??1;$('productStock').value=p.stock??0;$('productNotes').value=p.notes||'';$('productNoSub').checked=p.noSub!==false;$('deleteProductBtn').classList.remove('hidden');$('productDialog').showModal()};
window.changeQty=(id,d)=>{const i=data.currentShop.find(x=>x.productId===id);if(i){i.qty=Math.max(1,Number(i.qty)+d);saveData()}};window.removeShopItem=id=>{data.currentShop=data.currentShop.filter(x=>x.productId!==id);saveData()};
function openNewProduct(){['productId','productName','productBrand','productCategory','productPack','productNotes'].forEach(id=>$(id).value='');$('productDialogTitle').textContent='Add product';$('productSafety').value='approved';$('productQty').value=1;$('productStock').value=0;$('productNoSub').checked=true;$('deleteProductBtn').classList.add('hidden');$('productDialog').showModal()}
$('unlockBtn').onclick=unlock;$('pinInput').addEventListener('keydown',e=>{if(e.key==='Enter')unlock()});$('setupPinBtn').onclick=setupPin;$('lockBtn').onclick=()=>{$('app').classList.add('hidden');$('lockScreen').classList.remove('hidden')};document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>showView(t.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$('addProductBtn').onclick=openNewProduct;$('closeDialog').onclick=()=>$('productDialog').close();$('productSearch').oninput=renderProducts;$('safetyFilter').onchange=renderProducts;
$('productForm').onsubmit=e=>{e.preventDefault();const id=$('productId').value||uid();const existing=data.products.find(p=>p.id===id);const p={id,name:$('productName').value.trim(),brand:$('productBrand').value.trim(),category:$('productCategory').value.trim(),pack:$('productPack').value.trim(),safety:$('productSafety').value,usualQty:Number($('productQty').value)||0,stock:Number($('productStock').value)||0,notes:$('productNotes').value.trim(),noSub:$('productNoSub').checked};if(existing)Object.assign(existing,p);else data.products.push(p);$('productDialog').close();saveData();toast('Product saved.')};
$('deleteProductBtn').onclick=()=>{const id=$('productId').value;if(confirm('Delete this product and its saved prices?')){data.products=data.products.filter(p=>p.id!==id);data.prices=data.prices.filter(p=>p.productId!==id);data.currentShop=data.currentShop.filter(p=>p.productId!==id);$('productDialog').close();saveData();toast('Product deleted.')}};
$('priceForm').onsubmit=e=>{e.preventDefault();data.prices.push({id:uid(),productId:$('priceProduct').value,store:$('priceStore').value,price:Number($('priceValue').value),pack:$('pricePack').value.trim(),unit:$('priceUnit').value.trim(),special:$('priceSpecial').checked,date:new Date().toISOString()});e.target.reset();saveData();toast('Price saved.')};
$('bulkPriceForm').onsubmit=e=>{e.preventDefault();const store=$('bulkStore').value;let count=0;for(const line of $('bulkPrices').value.split(/\n+/)){const [name,price,pack='']=line.split('|').map(x=>x.trim());if(!name||!price)continue;const p=data.products.find(x=>x.name.toLowerCase()===name.toLowerCase()||x.name.toLowerCase().includes(name.toLowerCase())||name.toLowerCase().includes(x.name.toLowerCase()));if(p&&!isNaN(Number(price))){data.prices.push({id:uid(),productId:p.id,store,price:Number(price),pack,unit:'',special:false,date:new Date().toISOString()});count++}}$('bulkPrices').value='';saveData();toast(`${count} price${count===1?'':'s'} imported.`)};
$('addAllDueBtn').onclick=()=>{for(const p of data.products.filter(p=>p.safety==='approved')){const q=suggestedQty(p);if(q>0&&!data.currentShop.some(i=>i.productId===p.id))data.currentShop.push({productId:p.id,qty:q})}saveData();toast('Due approved products added.')};
$('completeShopBtn').onclick=()=>{if(!data.currentShop.length){toast('Your shopping list is empty.');return}const items=data.currentShop.map(i=>{const p=data.products.find(x=>x.id===i.productId),b=p?bestFor(p):{price:0,store:''};if(p)p.stock=Number(p.stock||0)+Number(i.qty||0);return{...i,store:b.store,unitPrice:b.price}});const total=items.reduce((s,i)=>s+i.qty*i.unitPrice,0);data.history.push({id:uid(),date:new Date().toISOString(),items,total});data.settings.lastShopDate=new Date().toISOString();data.currentShop=[];saveData();toast('Shop completed and learning history updated.')};
$('settingsForm').onsubmit=e=>{e.preventDefault();data.settings.cycleDays=Number($('cycleDays').value);data.settings.minimumSpend=Number($('minimumSpend').value);data.settings.traceDairy=$('traceDairy').checked;saveData();toast('Settings saved.')};
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`genevieve-smart-shop-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const imported=JSON.parse(await file.text());if(!imported.products||!imported.settings)throw new Error('Invalid');data=imported;saveData();toast('Backup restored.')}catch{toast('That backup file could not be read.')}e.target.value=''};
$('clearBtn').onclick=()=>{if(confirm('Erase all products, prices and history from this browser? This cannot be undone without a backup.')){data=structuredClone(defaultData);localStorage.removeItem(KEY);saveData();toast('All app data erased.')}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')};if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
renderAll();
